config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  root to: "events#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  
  resources :events do
    collection do
      get 'search'
      get 'about'
      get 'about_me'
    end
    resources :comments
    resources :likes, only: [:create, :destroy]
    resources :joins do
      collection do
        # デフォルト形式をcsvに設定
        get :csv_download, defaults: { format: 'csv' }
      end
    end
  end

  resources :users
  put "/users/:id/withdrawal" => "users#withdrawal", as: 'users_withdrawal'
  
end

app/views/shared/_back.html.erb
<%= link_to image_tag('矢印ボタン　左3.png', class: "back-btn"), :back %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
    <p>
      Copyright Uni-chann 2020.
    </p>
</footer>

app/views/shared/_form.html.erb
      <div class="form-1">
        <%= f.label :イベントイメージ画像, class: 'form-item' %><br />
        <%= f.file_field :images, direct_upload: true, multiple: true, class:'form-file-field' %>
        <div id="event-images"></div>
        <p>※クリックしてファイルをアップロード</p>
        <p><%= f.check_box :remove_images %>画像を削除する</p>
      </div>

      <div class="form-1">
        <%= f.label :イベントの種類, class: 'form-item' %><br />
        <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>

      <div class="form-1">
        <%= f.label :イベント名, class: 'form-item' %><br />
        <%= f.text_area :project, class: "form-text" %>
      </div>

      <div class="form-1">
        <%= f.label :イベント概要, class: 'form-item' %><br />
        <%= f.text_area :overview, class: "form-text" %>
      </div>

      <div class="form-1">
        <%= f.label :開催予定日時, class: 'form-item' %><br />
        <%= f.date_field :date, class: "form-text" %>
      </div>

      <div class="form-1">
        <%= f.label :メールアドレス（連絡先）, class: 'form-item' %><br />
        <%= f.text_area :email, placeholder:"参加者との連絡が可能なアドレス", class: "form-text" %>
      </div>

      <div class="form-1">
        <%= f.label :電話番号, class: 'form-item' %><br />
        <%= f.telephone_field :phone, placeholder:"例）090-1111-1111", class: "form-text" %>
      </div>

      <div class="form-1">
        <%= f.label :開催場所（住所）, class: 'form-item' %><br />
        <%= f.text_area :address, placeholder:"例)東京都港区六本木1-1-1", class: "form-text" %>
      </div>

app/views/shared/_header.html.erb
<header class="header">
    <div class="header-p">
      <div class="header-2">
        <%# <h2><a href="/">Uni＊Chann</a></h2> %>
        <%= link_to image_tag('unirogo.png', class: "unirogo"), root_path%>
      </div>
      <div class="header-3">
        <span class="nav_toggle">
          <i></i>
          <i></i>
          <i></i>
        </span>
 
        <%# ユーザーがログイン済みの場合表示条件分岐で表示を変える %>
        <% if user_signed_in? %>
        <nav class="nav">
          <ul class="nav_menu_ul">
            <li class="nav_menu_li"><%= link_to "Uni＊Channとは", about_events_path %></li>
            <li class="nav_menu_li"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
          </ul>
        </nav>
          <div class="login-user-image">
            <% if current_user.image.attached? %>
              <div class="login-underbar-cancel">
              <li class="nav_menu_li"><%= link_to image_tag(current_user.image, class: "user-img" ), edit_user_registration_path %></li>
              </div>
            <% else %>
              <div class="login-underbar-cancel">
              <li class="nav_menu_li"><%= link_to image_tag('人物の無料素材.png', class: "user-img" ), edit_user_registration_path %></li>
            <%# <li><%= link_to current_user.nickname, edit_user_registration_path, class: "user-nickname" %></li>
              </div>
            <% end %>
          </div>
          <% else %>
          <nav class="nav">
            <ul class="nav_menu_ul">
              <li class="nav_menu_li"><%= link_to "Uni＊Channとは", about_events_path %></li>
              <li class="nav_menu_li"><%= link_to "ログイン", new_user_session_path, class: "login-1"%></li>
              <li class="nav_menu_li"><%= link_to "新規登録", new_user_registration_path, class: "sign-up" %></li>
              <li class="nav_menu_li"><%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post %></li>
            </ul>
          </nav>
        <% end %>
      </div>
    </div>
</header>

app/views/shared/_howto.html.erb
<div class="title-ex-box-index ">
  <div class="title-ex-index ">
    <h3>Uni＊Channの使い方</h3>
    <h4>~地域イベント、ワークショップのマッチングアプリ~</h4>
  </div>
  <div class="howto-index ">
    <div class="howto-post-index ">
      <div class="howto-title-index ">
        <h4>見つける</h4>
      </div>
      <div class="howto-img-index ">
        <%= image_tag '虫眼鏡のアイコン (1).png' , size: '100x100' %>
      </div>
      <div class="howto-content-index ">
      
        <p>お好みのイベントを見つけたらイベントをクリック。
        気に入ったら<b>「Join!」</b>から参加登録しましょう！
        参加済みのイベントにはアイコン(<%= image_tag 'humangray.png', class: "event-join-mark-mini"%>)が表示されますのでひと目で確認できます！
        イベントについて不明点があればコメント機能を活用して質問してみるのも良いでしょう。
        

        </p>
        
      </div>
    </div>

    <div class="howto-post-index ">
      <div class="howto-title-index ">
        <h4>投稿する</h4>
      </div>
      <div class="howto-img-index ">
        <%= image_tag 'えんぴつ付きのノートアイコン.png' , size: '100x100' %>
      </div>
      <div class="howto-content-index ">
        <p>
        イベントを投稿してみましょう。画面右下の<b>「New!」</b>からあなたがホストの新しいイベントの作成が可能です。
        ホストは参加者一覧を表示することができます。
        あなたがホストの場合はイベントにアイコン(<%= image_tag '丸枠の中に王冠を配置したアイコン素材.png', class: 'event-owners-mark-mini'%>)が表示されます！
        必要であればcsvファイルにも出力(PC版ブラウザ)できるのでリスト管理が楽々です。
        
        </p>
      </div>
    </div>

    <div class="howto-post-index ">
      <div class="howto-title-index ">
        <h4>体験する</h4>
      </div>
      <div class="howto-img-index ">
        <%= image_tag 'チアリーダーのピクトグラム.png' , size: '100x100' %>
      </div>
      <div class="howto-content-index ">
        <p>
        登録したイベントを存分に楽しみましょう。
        イベントのコメント欄に感想をつぶやいても良いかもしれません。
        「いいね！」(<%= image_tag 'ハートのアイコン素材 1.png', class: "event-index-like-image3-mini"%>)をつけたり、お使いのSNSサービスにどんどん共有してイベントを盛り上げあなたの地域の活動を世界中に見てもらいましょう！
        </p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_searchbar.html.erb
<div class="search-bar">
  <div class="search-p">
    <%= search_form_for @p, url: search_events_path do |f| %>
      <div class="search-box">
        <%# <h4>イベントを探す</h4> %>
        <div class="search-box-1">
          <div class="search-text">カテゴリ</div>
          <div>
            <%= f.collection_select :genre_id_eq, Genre.where.not(id: 0), :id, :name, include_blank: '指定なし', class: "search-category-field" %>
          </div>
          <div class="search-box-2">
            <%= f.text_field :project_or_overview_or_address_cont, placeholder: "ワードで検索(カテゴリ指定のみでも検索可能)", class: "search-input" %>
          </div>
          <div class ="search-box-3">
            <%= f.submit '検索', class: "search-btn"%>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>