config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  root to: "events#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  
  resources :events do
    collection do
      get 'search'
      get 'about'
      get 'about_me'
    end
    resources :comments
    resources :likes, only: [:create, :destroy]
    resources :joins do
      collection do
        # デフォルト形式をcsvに設定
        get :csv_download, defaults: { format: 'csv' }
      end
    end
  end

  resources :users
  put "/users/:id/withdrawal" => "users#withdrawal", as: 'users_withdrawal'
  
end

app/models/event.rb
class Event < ApplicationRecord
  is_impressionable counter_cache: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  
  has_many_attached :images
  belongs_to_active_hash :genre
  belongs_to :user
  has_many :joins
  has_many :comments
  has_many :likes
  has_many :liked_users, through: :likes, source: :user

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  with_options presence: true do
    validates :images
    validates :overview, length: { in: 1..400, message: 'は400文字以内です' }
    validates :project, length: { in: 1..50, message: 'は50文字以内です' }
    validates :address
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, format: { with: VALID_EMAIL_REGEX }
    validates :date
    VALID_PHONE_REGEX = /\A\d{10}$|^\d{11}\z/
    validates :phone, format: { with: VALID_PHONE_REGEX }
  end

  validates :genre_id, numericality: { other_than: 0, message: 'が選択されていません' }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # impressionist :actions=> [:show, :index], :unique => [:impressionable_id, :ip_address]
  before_action :authenticate_user!, only: [:new, :create, :edit, :destroy, :update]
  before_action :set_event, only: [:edit, :show, :update]
  before_action :search_event, only: [:index, :search]

  def index
    @events = Event.all.page(params[:page]).per(15).order('updated_at DESC')
    set_event_column 
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.create(event_params)
    if @event.save
      redirect_to root_path, notice: "新しいイベントが投稿されました" 
    else
      render :new
    end
  end

  def destroy
    event = Event.find(params[:id])
    if event.destroy
      redirect_to root_path, alert: "イベントは削除されました"
    end
  end

  def edit
    if current_user.id != @event.user.id
      redirect_to root_path 
    end
  end

  def search
    @results = @p.result
  end

  def show
    @comment = Comment.new
    @comments = Comment.where(event_id: @event)
    @like = Like.new
    impressionist(@event, nil, unique: [:impressionable_id, :ip_address])
    
    @views = @event.impressionist_count
  end

  def update
    @event.update(event_params)
    if @event.save
      redirect_to root_path, notice: "イベント情報が更新されました" 
    else
      render :edit
    end
  end

  private

  def event_params
    params.require(:event).permit(:genre_id, :project, :overview, :date, :email, :phone, :address, images: []).merge(user_id: current_user.id)
    # active storage画像複数枚投稿
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def search_event
    @p = Event.ransack(params[:q])
  end

  def set_event_column
    @event_name = Event.select("name").distinct  # 重複なくnameカラムのデータを取り出す
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/about_me.html.erb
<div class="about_me_all">
  <div class="left_contents">
    <div class="me_title">
      <div class="me_font">
        <h1>About Me</h1>
      </div>
    </div>
    <div class="me_overview">
      <div class="me_overview_main">
        <ul class="me_overview_list">
          <li>Apple Japan合同会社でテクニカルサポートスペシャリストを経験。ソフトウェアの知識、エンドユーザーや社内エンジニアとのコミュニケーションから得た体験を元に自らの手でサービスを構築、運用できるwebエンジニアを志し転職活動開始。</li>
          <br>
          <li>サービスの設計、実装、運用、マネジメントを経験しwebの力で課題を解決したい。生業とすることを目標。</li>
        </ul>
          <p>◆好きな言葉◆　日々是好日</p>
          <p>◆長所◆　探究心/好奇心/粘り強さ</p>
          <p>◆短所◆　深く思考しすぎて灯台下暗し状態な時がある</p>
          <p>◆趣味◆　写真/つくること全般/ドリップコーヒー（豆の焙煎から）</p>
      </div>
    </div>
    <div class="me_link">
      <div class="me_link_main">
          <div class="me_link_child">
            <div>
              <%= image_tag('uni.png', class: "link_image")%>
            </div>
            <div class="link_url">
              <div>
                <a href="https://www.unichann.com/">https://www.unichann.com/</a>
              </div>
            </div>
          </div>
          <div class="me_link_child">
            <div>
              <%= image_tag('twitter_noback.png', class: "link_image")%>
            </div>
            <div class="link_url">
              <div>
                <a href="https://twitter.com/engineer_peeta">https://twitter.com/engineer_peeta</a>
              </div>
            </div>
          </div>
          <div class="me_link_child">
            <div>
              <%= image_tag('GitHub-Mark-120px-plus.png', class: "link_image")%>
            </div>
            <div class="link_url">
              <div>
                <a href="https://github.com/KeitaSasaki505">https://github.com/KeitaSasaki505</a>
              </div>
            </div>
          </div>
      </div>
    </div>
    <div class="me_signature">
      <div class="me_signature_place">
        <%= image_tag('signature.png', class: 'me_signature_size') %>
      </div>
    </div>
  </div>

  <div class="right_contents" style="background_image:url(<%= asset_path "DSC00089.jpg" %>)">
  </div>
</div>

app/views/events/category.html.erb
<%= render 'shared/header' %>

  <div class="event-p">
    <div class="event-list">
      <% @events.each do |event| %>
        <li class='list'>
          <%= link_to event_path(event.id) do %>
            <div class="event-img-join">
              <div class='event-img-content'>
                <%= image_tag(event.images[0].variant(resize: '300x300'), class: "event-img-index")  if event.images.attached?%>
              </div>
              <% if user_signed_in? && current_user.id == event.user.id %>
                <%= image_tag '丸枠の中に王冠を配置したアイコン素材.png', class: "event-owners-mark" %>
              <% elsif user_signed_in? && current_user.id &&  (event.joins.find_by(user_id: current_user.id)) != nil %>
                <%= image_tag 'humangray.png', class: "event-join-mark" %>
              <% end %>
            </div>
            <div class='event-info'>
              <h3 class='event-name'>
                <%= event.project %>
              </h3>
              <div class="event-ex">
                <%= event.overview %>
              </div>
              <div class='event-date'>
                <span>開催予定日：<%= event.date %></span>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
    </div>
  </div>

    <div class='event-btn'>
      <span class='event-btn-text'>New!</span>
      <a href="/events/new">
        <%= image_tag '万年筆の無料アイコン素材.png' , size: '185x50' ,class: "event-btn-icon" %>
      </a>
    </div>

<%= render 'shared/footer' %>

app/views/events/edit.html.erb
<%= render 'shared/header' %>
<%= render 'shared/back'%>
<%# <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
<%= form_with model: @event, class: 'registration-main', local: true do |f| %>
  <div class="form-main">
    <div class="form-edit">
      <h3>
      イベントを編集する
      </h3>
      
      <%= render 'shared/error_messages', model: f.object %>
      <div class="form-2">
        <label for="event-image" class="form-item", id="file-field">
        <span>イベントイメージ画像をアップロード(3枚まで)</span>
        <%= f.file_field :images, name: 'event[images][]', id: "event-image", direct_upload: true, multiple: true, data: {index:0}, class:'form-file-field' %>
        </label>
      </div>
      
      <div id="pre-images" class="pre-imagesbox"></div>

      <div class="form-1">
        <%= f.label :イベントの種類%><br />
        <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>

      <div class="form-1">
        <%= f.label :イベント名%><br />
        <%= f.text_area :project, class: "form-text" %>
      </div>

      <div class="form-1">
        <%= f.label :イベント概要%><br />
        <%= f.text_area :overview, class: "form-text" %>
      </div>

      <div class="form-1">
        <%= f.label :開催予定日時%><br />
        <%= f.date_field :date, class: "form-text" %>
      </div>

      <div class="form-1">
        <%= f.label :メールアドレス（連絡先） %><br />
        <%= f.text_area :email, placeholder:"参加者との連絡が可能なアドレス", class: "form-text" %>
      </div>

      <div class="form-1">
        <%= f.label :電話番号 %><br />
        <%= f.telephone_field :phone, placeholder:"例）09011111111", class: "form-text" %>
      </div>

      <div class="form-1">
        <%= f.label :開催場所（住所） %><br />
        <%= f.text_area :address, placeholder:"例)東京都港区六本木1-1-1", class: "form-text" %>
      </div>
    
      <div class ="form-edit-btn">
        <%= f.submit "イベントを更新", class:"form-submit" %>
      </div>
      
    </div>
  </div>
<% end %>

app/views/events/edit.index.erb
<h2>イベントの編集</h2>

<%# <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
<%= form_with model: @event, class: 'registration-main', local: true do |f| %>

  <h3 class='form-header-text'>
    イベントを編集する
  </h3>
  <div class="field">
    <%= f.label :イベントイメージ画像 %><br />
    <%= f.file_field :image %><p>※クリックしてファイルをアップロード</p>
  </div>

  <div class="field">
    <%= f.label :イベントの種類 %><br />
    <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
  </div>

  <div class="field">
    <%= f.label :イベント名 %><br />
    <%= f.text_area :project %>
  </div>

  <div class="field">
    <%= f.label :イベント概要 %><br />
    <%= f.text_area :overview %>
  </div>

  <div class="field">
    <%= f.label :開催予定日時 %><br />
    <%= f.date_field :date %>
  </div>

  <div class="field">
    <%= f.label :メールアドレス（連絡先） %><br />
    <%= f.text_area :email, placeholder:"参加者との連絡が可能なアドレス" %>
  </div>

  <div class="field">
    <%= f.label :電話番号 %><br />
    <%= f.telephone_field :phone, placeholder:"例）090-1111-1111" %>
  </div>

  <div class="field">
    <%= f.label :開催場所（住所） %><br />
    <%= f.text_area :address, placeholder:"例)東京都港区六本木1-1-1"%>
  </div>

  <%= f.submit "イベントを投稿する" ,class:"" %>
<% end %>

app/views/events/index.html.erb
<%= render 'shared/header'%>
<%= render 'shared/searchbar'%>
<%= render 'layouts/flash' %>



  <div class="event-p">
  <div class="howto-index">
  <%= render 'shared/howto' %>
  
  </div>
    <div class="event-list">
      <% @events.each do |event| %>
        <li class='list'>
          <%= link_to event_path(event.id) do %>
            <div class="list-inner">
              <div class="event-img-join">
                <div class='event-img-content'>
                  <%= image_tag(event.images[0].variant(resize: '280x280'), class: "event-img-index")  if event.images.attached?%>
                </div>
                <% if user_signed_in? && current_user.id == event.user.id %>
                  <%= image_tag '丸枠の中に王冠を配置したアイコン素材.png', class: "event-owners-mark" %>
                <% elsif user_signed_in? && current_user.id &&  (event.joins.find_by(user_id: current_user.id)) != nil %>
                  <%= image_tag 'humangray.png', class: "event-join-mark" %>
                <% end %>
              </div>
              <div class='event-info'>
                <h3 class='event-name'>
                  <%= event.project %>
                </h3>
                <div class="event-ex">
                  <%= event.overview %>
                </div>
                <div class='event-date'>
                  <span>開催予定日：<%= event.date %></span>
                </div>
              
                <div class="event-index-like-box">
                  <div class="event-index-set">
                    <%= image_tag 'ハートのアイコン素材 1.png', class: "event-index-like-image" %>
                    <%= event.likes.count%>
                  </div>
                  <div class="event-index-set">
                    <%= image_tag '双眼鏡アイコン4.png', class: "event-index-like-image" %>
                    <%=  event.impressionist_count %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
    </div>
    <div class="pagenation">
      <%= paginate @events %>
    </div>
  </div>

    <div class='event-btn'>
      <span class='event-btn-text'>New!</span>
      <a href="/events/new">
        <%= image_tag '万年筆の無料アイコン素材.png' , size: '185x50' ,class: "event-btn-icon" %>
      </a>
    </div>

app/views/events/new.html.erb
<%= render 'shared/header'%>
<%= render 'shared/back'%>

<%# <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
<%= form_with model: @event, class: 'registration-main', local: true do |f| %>
  
  <div class="form-main">
    <div class="form-edit">
      <h3 class='form-header-text'>
      新しいイベントを投稿する
      </h3>
      
      <%= render 'shared/error_messages', model: f.object %>
      
      <div class="form-2">
        <label for="event-image" class="form-item" id="file-field">
        <span>イベントイメージ画像をアップロード(3枚まで)</span>
        <%= f.file_field :images, name: 'event[images][]', id: "event-image", multiple: true, data: {index:0}, class:'form-file-field' %>
        <%# エラーになる可能性の箇所のため退避 direct_upload: true, %>
        </label>
      </div>
      
      <div id="pre-images" class="pre-imagesbox"></div>

      <div class="form-1">
        <%= f.label :イベントの種類 %><br />
        <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>

      <div class="form-1">
        <%= f.label :イベント名%><br />
        <%= f.text_area :project, placeholder: "50文字以内", class: "form-text" %>
      </div>

      <div class="form-1">
        <%= f.label :イベント概要%><br />
        <%= f.text_area :overview, placeholder: "400文字以内", class: "form-text" %>
      </div>

      <div class="form-1">
        <%= f.label :開催予定日時%><br />
        <%= f.date_field :date, class: "form-text" %>
      </div>

      <div class="form-1">
        <%= f.label :メールアドレス（連絡先） %><br />
        <%= f.text_area :email, placeholder:"例）abcde@sample.com", class: "form-text" %>
      </div>

      <div class="form-1">
        <%= f.label :電話番号 %><br />
        <%= f.telephone_field :phone, placeholder:"例）09011111111", class: "form-text"%>
      </div>

      <div class="form-1">
        <%= f.label :開催場所（住所）%><br />
        <%= f.text_area :address, placeholder:"例)東京都港区六本木1-1-1", class: "form-text" %>
      </div>
    
      <div class="form-edit-btn">
        <%= f.submit "イベントを投稿", class:"form-submit" %>
      </div>
    </div>
  </div>
<% end %>

app/views/events/search.html.erb
<%= render 'shared/header' %>
<%= render 'shared/searchbar'%>

  <div class="event-p">
    <div class="event-list">
      <% @results.each do |event| %>
        <li class='list'>
          <%= link_to event_path(event.id) do %>
            <div class="event-img-join">
              <div class='event-img-content'>
                <%= image_tag(event.images[0].variant(resize: '300x300'), class: "event-img-index")  if event.images.attached?%>
              </div>
            <% if user_signed_in? && current_user.id == event.user.id %>
              <%= image_tag '丸枠の中に王冠を配置したアイコン素材.png', class: "event-owners-mark" %>
            <% elsif user_signed_in? && current_user.id &&  (event.joins.find_by(user_id: current_user.id)) != nil %>
              <%= image_tag 'humangray.png', class: "event-join-mark" %>
            <% end %>
            </div>
            <div class='event-info'>
              <h3 class='event-name'>
                <%= event.project %>
              </h3>
              <div class="event-ex">
                <%= event.overview %>
              </div>
              <div class='event-date'>
                <span>開催予定日：<%= event.date %></span>
              </div>
              <div class="event-index-like-box">
              <div class="event-index-set">
                <%= image_tag 'ハートのアイコン素材 1.png', class: "event-index-like-image" %>
                <%= event.likes.count%>
              </div>
              <div class="event-index-set">
                <%= image_tag '双眼鏡アイコン4.png', class: "event-index-like-image" %>
                <%=  event.impressionist_count %>
              </div>
            </div>
            </div>
          <% end %>
        </li>
      <% end %>
    </div>
  </div>

    <div class='event-btn'>
      <span class='event-btn-text'>New!</span>
      <a href="/events/new">
        <%= image_tag '万年筆の無料アイコン素材.png' , size: '185x50' ,class: "event-btn-icon" %>
      </a>
    </div>

app/views/events/show.html.erb
<%= render 'shared/header' %>
<%= render 'shared/back'%>
<div class="show">
  <div class="show-2">
    <ul class="show-3">
      <div class="show-title">
        <div class="show-title-text">【<%= @event.genre.name %>】<%= @event.project %></div>
      </div>
      
      <% if @event.images.attached?%>
      <div class="image-all">
        <div class="image-box">
          <div class="main-image">
            <%= image_tag(@event.images[0].variant(resize: '600x400'), class: "event-img") %>
          </div>

          <div class="sub-image-box">
            <% @event.images[1..2].each do |image| %>
              <div class="sub-image">
                <%= image_tag(image.variant(resize: '195x195'), class: "event-img-sub") %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>

      <div class="event-index-like-box2">
        <div class="event-index-set">
          <div class ="event-like-view-set">
            <% if user_signed_in? %>
              <div class="goodimage-count">
                <% if current_user.already_liked?(@event) %>
                  <%= link_to image_tag('ハートのアイコン素材 1.png', class: "event-index-like-image3"), event_like_path(@event), method: :delete, title: 'いいね！キャンセル'%>
                <% else %>
                  <%= link_to image_tag('ハートのアイコン素材 1.png', class: "event-index-like-image3"), event_likes_path(@event), method: :post, title: 'いいね！を押す' %>
                <% end %>
              </div>
            <% else %>
              <%= image_tag 'ハートのアイコン素材 1.png', class: "event-index-like-image3", data: { confirm: "ログインするといいね！が押せます" }%>
            <% end %>
            
            <div class="goodimage-count">
              <%= @event.likes.count %>
            </div>
          </div>

          <div class="event-like-view-set">
            <div class="like-dis">
              <%= image_tag '双眼鏡アイコン4.png', class: "event-index-like-image2", title: "閲覧数" %>
              <%=  @event.impressionist_count %>
            </div>
          </div>
        </div>

        <div class="sns-set">
          <div class="event-index-set">
            <%= link_to image_tag('twitterのアイコン素材 その2.png', class: "event-index-like-image3"), "https://twitter.com/share?url=#{request.url}", title: 'Twitter', target: '_blank' %>
          </div>
          <div class="event-index-set">
            <%= link_to image_tag('round-default.png', class: "event-index-like-image3"), "https://social-plugins.line.me/lineit/share?url=#{request.url}", title: 'LINE', target: '_blank' %>
          </div>
          <div class="event-index-set">
            <%= link_to image_tag('FACEBOOK風のアイコン素材.png', class: "event-index-like-image3"), "https://www.facebook.com/sharer/sharer.php?u=#{request.url}", title: 'facebook', target: '_blank' %>
          </div>
        </div>
      </div>

      <div class="eventer">
        <h3 class="event-sub-title">イベント主催者</h3>
        <div class="eventer-field">
          <div class="event-detail-image">
            <% if @event.user.image.attached? %>
              <%= image_tag(@event.user.image.variant(resize: '60x60'), class: "eventer-image") %>
            <% else %>
              <%= image_tag('人物の無料素材.png', class: "eventer-image" ) %>
            <% end %>
          </div>
          <div class="eventer-nickname">
            <%= @event.user.nickname %>
          </div>
        </div>
      </div>

        <h3 class="event-sub-title">イベント内容</h3>
        <div class="eventer-field">        
          <%= @event.overview %>
        </div>

      <h3 class="event-sub-title">開催予定日時</h3>
        <div class="eventer-field">
          <%= @event.date %>
        </div>

      <h3 class="event-sub-title">開催場所</h3>
        <div class="eventer-field">
          <%= @event.address %>
        </div>

    <%# ----------------googlemap API -------------------%>
    <h3 class="event-sub-title">開催場所詳細</h3>

      <div class="eventer-field">
        <script type="text/javascript">
          function initMap() {
        // latitude,longitudeから位置を特定
            const test ={lat: <%= @event.latitude %>, lng: <%= @event.longitude %> };
            const map = new google.maps.Map(document.getElementById('map'), {
                      zoom: 15, 
                      center: test
                      });
            const transitLayer = new google.maps.TransitLayer();
            transitLayer.setMap(map);

            const contentString = '住所：<%= @event.address %>';
            const infowindow = new google.maps.InfoWindow({
              content: contentString
            });

        //  Map上の指定した位置にピンを挿して表示する
            const marker = new google.maps.Marker({
                          position:test,
                          map: map,
                          title: contentString
                        });

            marker.addListener('click', function() {
              infowindow.open(map, marker);
            });
          }
        </script>

        <script async defer
                      src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap">
                      
        </script>

        <%# <script async defer
                      src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>
                      <%# &callback=initMap"> %>
                      
        <%# </script> %>

        <style type="text/css">
          #map { height: 400px;
                width: 640px;}
        </style>

        <%# #mapの表示 %>
        <div id="map"></div>
      </div>

    <%# ----------------googlemap API -------------------%>


          <div class="join-entry">
            <% if user_signed_in? && current_user.id == @event.user.id %>
              <ul class="join-list">
                <li>
                  <div class="edit-btn">
                    <span class="edit-btn-text">Edit!</span>
                    <%= link_to image_tag('太いリロードアイコン.png', class: "edit-icon"), edit_event_path, method: :get %>
                  </div>
                </li>
                <li>
                  <div class="join-list-btn">
                    <span class="join-list-text">List!</span>
                    <%= link_to image_tag('本棚のアイコン 2.png', size: '100x90', class: 'join-list-icon'), event_joins_path(@event.id) %>
                  </div>
                </li>
                <li>
                  <div class="event-destroy-btn">
                    <span class="event-destroy-text">delete</span>
                    <%= link_to image_tag('バックスペースのアイコン素材2.png', size: '100x90', class: 'event-destroy-icon'), event_path(@event.id), method: :delete, data: { confirm: "このイベントを削除してもよろしいですか?" } %>
                  </div>
                </li>
              </ul>
            <% elsif user_signed_in? && ( current_user.id != @event.user_id ) && (@event.joins.find_by(user_id: current_user.id)) == nil%>
              <div class="join-btn">
                <span class="join-btn-text">Join!</span>
                <%= link_to image_tag('ランニングアイコン2.png', size: '70x70', class: 'join-btn-icon'), new_event_join_path(@event.id) %>
              </div>
            <% elsif user_signed_in? && ( current_user.id != @event.user_id ) && (@event.joins.find_by(user_id: current_user.id)) != nil%>
              <div class="join-done-btn">
                <span class="joined-btn-text" >Registered!</span>
                <%= link_to image_tag('グッジョブの手の無料アイコン2.png', size: '70x70', class: 'join-done-icon') %>
              </div>
            <% end %>
          </div>

        <h3 class="event-sub-title">コメント</h3>
        <div class="comment-main">
          <% @comments.each do |comment| %>
            <div class="post-all">
              <div class="post">
                <div class="post-content-img">
                <%# オーナーがコメントした場合はアイコンにマーク %>
                  <% if comment.user_id == @event.user_id %>
                    <div class="comment-owner">
                      <% if comment.user.image.attached? %>
                        <div>
                          <%= image_tag '丸枠の中に王冠を配置したアイコン素材.png', class: "user-owner-img" %>
                          <%= image_tag comment.user.image, class: "comment-owner-img" %>
                        </div>
                      <% else %>
                        <div>
                          <%= image_tag '丸枠の中に王冠を配置したアイコン素材.png', class: "user-owner-img" %>
                          <%= image_tag '人物の無料素材.png', class: "comment-owner-img" %>
                        </div>
                      <% end %>
                    </div>
                  <% else %>
                    <% if comment.user.image.attached? %>
                      <div>
                        <%= image_tag comment.user.image, class: "comment-owner-img" %>
                      </div>
                    <% else %>
                      <div>
                        <%= image_tag '人物の無料素材.png', class: "comment-owner-img" %>
                      </div>
                    <% end %>
                  <% end %>
                </div>
                <div class="post-side">
                  <div class="post-content-username">
                    <%= comment.user.nickname %>
                  </div>
                  <div class="post-content-txt">
                    <%= comment.text %>
                  </div>
                  <div class="post-date">
                    <%= comment.created_at.to_s(:datetime_jp) %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>

      <div class="post-comment-form-main">
        <div class="post-comment-form">
          <%= form_with(model:[@event, @comment], url: event_comments_path(@event.id), local: true) do |f|%>
              <%= f.text_field :text, class: 'message', placeholder: 'イベントへのコメント入力欄' %>
              <%= f.submit '送信', class: 'comment-btn' %>
          <% end %>
        </div>
      </div>
    </ul>
  </div>
</div>